### ISSUE TITLE
Why are we still processing data from November?

### ISSUE THREAD

**Issue by fbarreir** [PanDAWMS/panda_logstash_config#1]
Hi Aleksandr,
I see a lot of old messages in today's ElasticSearch index. Looking at the logstash logs, I see messages with old timeEvent fields are still being processed. Can you please check why?
Thanks,
Fernando

[root@aipanda145 logstash]# hostname
aipanda145.cern.ch
[root@aipanda145 logstash]# pwd
/var/log/logstash
[root@aipanda145 logstash]# zgrep "2016-11" logstash.log-*.gz
...
**logstash.log-20161210.gz**:{:timestamp=>"2016-12-09T12:43:48.733000+0100", :message=>"Failed action. ", :status=>400, :action=>["index", {:_id=>nil, :_index=>"atlas_pandalogs-2016.12.09", :_type=>"finisher", :_routing=>nil}, #<LogStash::Event:0x51f7ce60 @metadata={"type"=>"finisher", "beat"=>"pandalogs"}, @accessors=#<LogStash::Util::Accessors:0x5e133237 @store={"@version"=>1, "@timestamp"=>"2016-12-09T11:42:45.304Z", "source"=>"/var/log/panda/panda-Finisher.log", "type"=>"finisher", "count"=>1, "beat"=>{"hostname"=>"aipanda036.cern.ch", "name"=>"aipanda036.cern.ch"}, "offset"=>3420067, "input_type"=>"log", "fields"=>nil, "host"=>"aipanda036.cern.ch", "tags"=>["beats_input_codec_plain_applied"], **"timeEvent"=>"2016-11-29 14:27:45,740"**, "logName"=>"panda.log.Finisher", "logLevel"=>"DEBUG", "message"=>"IDs: [3100819080, 3100819083, 3100819089, 3100819094, 3100819112, 3100819119, 3100819127, 3100819129, 3100819113, 3100819117, 3100819120, 3100819098, 3100819114, 3100819121, 3100819101, 3100819104, 3100819116, 3100819122, 3100819107, 3100819125, 3100819087, 3100819109, 3100819124]", "IDs"=>"3100819080, 3100819083, 3100819089, 3100819094, 3100819112, 3100819119, 3100819127, 3100819129, 3100819113, 3100819117, 3100819120, 3100819098, 3100819114, 3100819121, 3100819101, 3100819104, 3100819116, 3100819122, 3100819107, 3100819125, 3100819087, 3100819109, 3100819124"}, @lut={"@version"=>[{"@version"=>1, 
...

**Comment by Foorth** [comment]
IDs field have int type now. In this string IDs field is string type (or massive). it is the main reason of this error. One solution is to create new IDs field to IDsString for example.

**Comment by fbarreir** [comment]
it seems filebeat is not keeping up with logs (we don't think bottleneckt is on logstash, because jedi is up to date and jedi logs are smaller). I restarted the filebeat agents on panda machines so they come back to current date. literature to read on measuring filebeat performance and improving it:
https://discuss.elastic.co/t/filebeat-sending-data-to-logstash-seems-too-slow/37596
https://discuss.elastic.co/t/filebeat-not-keeping-up-with-logs/48980/2

**Comment by fbarreir** [comment]
I think it was solved with this commit:
https://github.com/PanDAWMS/panda_logstash_config/commit/17e69253764d8502d3d499e7bccc4c63b712e7d8
