### ISSUE TITLE
Conflicts in mappings

### ISSUE THREAD

**Issue by fbarreir** [PanDAWMS/panda_logstash_config#2]
Hi Aleksandr,
There are a lot of conflicts (string vs number) in the mappings since the update on the datatype. Can you please see how to reindex the data to resolve the conflict. If that's a lot of work, it could also be fine to remove the older indices. (But once we have more intensive use of our data this will not be a good solution)
Thanks,
Fernando
![screen shot 2016-12-14 at 14 41 13](https://cloud.githubusercontent.com/assets/1888554/21184247/dcd516f4-c20b-11e6-84ad-e76773428a09.png)

**Comment by Foorth** [comment]
I can do reindex (but will have to remove the old indexes) https://dev.sobeslavsky.net/kibana-how-to-solve-mapping-conflict/ only with your permission.

**Comment by Foorth** [comment]
Done
